name: Insert Nade to JSON

on:
  issues:
    types: [labeled]

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Check aprove label
      if: github.event.label.name != 'nade aprovada'
      run: |
        echo "Label não é 'nade aprovada'. Encerrando workflow."
        exit 1

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub pandas requests

    - name: Run auto commit script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: |
        python scripts/auto_commit_nade.py

    - name: Close Issue
      if: github.event.label.name == 'nade aprovada'
      run: |
        curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          -d '{"state":"closed"}'

    - name: Trigger Deploy workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: trigger-deploy
